# Generated by Django 4.1.7 on 2023-04-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('genero', models.TextField(max_length=50)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
    ]
