# Generated by Django 4.1.7 on 2023-04-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesRate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
