# Generated by Django 4.1.7 on 2023-04-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamesRate', '0002_juego_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='precio',
            new_name='estrellas',
        ),
    ]
