# Generated by Django 4.1.7 on 2023-04-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamesRate', '0003_rename_precio_juego_estrellas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='descripcion',
            new_name='opinion',
        ),
    ]
