# Generated by Django 4.1.7 on 2023-04-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesRate', '0008_remove_juego_estrellas'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='estrellas',
            field=models.IntegerField(default=0),
        ),
    ]
