# Generated by Django 4.1.7 on 2023-04-22 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GamesRate', '0010_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
